# Generated by Django 4.2.2 on 2023-06-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('username', models.CharField(max_length=500, unique=True)),
                ('address', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=300)),
                ('pincode', models.IntegerField()),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
            ],
        ),
    ]
