# Generated by Django 4.2.2 on 2023-06-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='signup_as',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='pincode',
            field=models.CharField(max_length=200),
        ),
    ]
