# Generated by Django 4.2.2 on 2023-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_signup_signup_as_alter_signup_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
